server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            client-name: 'Yandex'
            scope:
              - iot:view
              - iot:control
            redirect-uri: '${application.properties.base-url}/login/oauth2/code/{registrationId}'
            authorization-grant-type: 'authorization_code'
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/kestarbot}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db/migration

application:
  properties:
    base-url: 'http://127.0.0.1:8080'

telegram:
  bot:
    enabled: true
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
