name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: timeweb-cloud
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven settings
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
        run: |
          mkdir -p $HOME/.m2
          printf "%s" "$MAVEN_SETTINGS" > $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kestar-telegram-bot:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/kestar-telegram-bot:latest
            docker stop kestar-bot || true
            docker rm kestar-bot || true
            docker run -d --name kestar-bot --network shared-network -p 8080:8080 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }} \
              -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
              -e YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }} \
              -e YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }} \
              -e APPLICATION_PROPERTIES_BASE_URL=${{ secrets.APPLICATION_PROPERTIES_BASE_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/kestar-telegram-bot:latest